CREATE DATABASE [NetflixStatistix]

ALTER DATABASE [NetflixStatistix] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NetflixStatistix] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NetflixStatistix] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NetflixStatistix] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NetflixStatistix] SET ARITHABORT OFF 
GO
ALTER DATABASE [NetflixStatistix] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NetflixStatistix] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NetflixStatistix] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NetflixStatistix] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NetflixStatistix] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NetflixStatistix] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NetflixStatistix] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NetflixStatistix] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NetflixStatistix] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NetflixStatistix] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NetflixStatistix] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NetflixStatistix] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NetflixStatistix] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NetflixStatistix] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NetflixStatistix] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NetflixStatistix] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NetflixStatistix] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NetflixStatistix] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [NetflixStatistix] SET  MULTI_USER 
GO
ALTER DATABASE [NetflixStatistix] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NetflixStatistix] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NetflixStatistix] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NetflixStatistix] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NetflixStatistix] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NetflixStatistix] SET QUERY_STORE = OFF
GO
USE [NetflixStatistix]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [NetflixStatistix]
GO
/****** Object:  Table [dbo].[Account]    Script Date: 4-1-2018 13:44:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[Abonneenummer] [int] IDENTITY(1,1) NOT NULL,
	[Naam] [varchar](50) NOT NULL,
	[Email] [varchar](60) NOT NULL,
	[Adres] [varchar](50) NOT NULL,
	[Woonplaats] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[Abonneenummer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Aflevering]    Script Date: 4-1-2018 13:44:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Aflevering](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Titel] [varchar](50) NOT NULL,
	[Tijdsduur] [time](7) NOT NULL,
	[SeizoenVolgnrCode] [int] NOT NULL,
	[TitelSerie] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Aflevering] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Film]    Script Date: 4-1-2018 13:44:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Film](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Titel] [varchar](50) NOT NULL,
	[Tijdsduur] [time](7) NOT NULL,
	[Genre] [varchar](50) NOT NULL,
	[Taal] [varchar](50) NOT NULL,
	[Leeftijd] [int] NOT NULL,
 CONSTRAINT [PK_Film] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profiel]    Script Date: 4-1-2018 13:44:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profiel](
	[Naam] [varchar](50) NOT NULL,
	[GebDatum] [date] NOT NULL,
 CONSTRAINT [PK_Profiel] PRIMARY KEY CLUSTERED 
(
	[Naam] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Serie]    Script Date: 4-1-2018 13:44:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Serie](
	[TitelSerie] [varchar](50) NOT NULL,
	[Genre] [varchar](50) NOT NULL,
	[Taal] [varchar](50) NOT NULL,
	[Leeftijd] [int] NOT NULL,
 CONSTRAINT [PK_Serie] PRIMARY KEY CLUSTERED 
(
	[TitelSerie] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Aflevering]  WITH CHECK ADD  CONSTRAINT [FK_Aflevering_Serie1] FOREIGN KEY([TitelSerie])
REFERENCES [dbo].[Serie] ([TitelSerie])
GO
ALTER TABLE [dbo].[Aflevering] CHECK CONSTRAINT [FK_Aflevering_Serie1]
GO
USE [master]
GO
ALTER DATABASE [NetflixStatistix] SET  READ_WRITE 
GO
